### ISSUE TITLE
zynq_remoteproc does not create rpmsg-openamp-demo-channel

### ISSUE THREAD

**Issue by gpresazzi** [OpenAMP/meta-openamp#2]
Hi all, 

I'm working with openAMP and zynq. The zynq_remoteproc start automatically when the system boots, but sometimes the rpmsg-openamp-demo-channel is not created successfully.
When that happens, the module modprobe rpmsg_user_dev_driver does not invoke the probe function.

Following some logs:

When the  zynq_remoteproc create rpmsg-openamp-demo-channel 
```
[    5.522347] remoteproc remoteproc0: loading /lib/firmware/updates/4.9.0-xilinx-v2017.1/firmware failed with error -2
[    5.522372] remoteproc remoteproc0: loading /lib/firmware/updates/firmware failed with error -2
[    5.522408] remoteproc remoteproc0: loading /lib/firmware/4.9.0-xilinx-v2017.1/firmware failed with error -2
[    5.626006] remoteproc remoteproc0: direct-loading firmware
[    5.636232] fw_set_page_data: fw-firmware buf=adca8440 data=b0a25000 size=569512
[    5.651873] remoteproc remoteproc0: powering up 0.zynq_remoteproc
[    5.659094] fw_set_page_data: fw-firmware buf=adca8440 data=b0a25000 size=569512
[    5.667931] remoteproc remoteproc0: Booting fw image firmware, size 569512
[    5.675222] device: 'virtio0': device_add
[    5.680143] bus: 'virtio': add device virtio0
[    5.688833] PM: Adding info for virtio:virtio0
[    5.709500] remoteproc remoteproc0: registered virtio0 (type 7)
[    5.718205] bus: 'rpmsg': registered
[    5.723214] bus: 'virtio': add driver virtio_rpmsg_bus
[    5.723237] bus: 'virtio': driver_probe_device: matched device virtio0 with driver virtio_rpmsg_bus
[    5.723245] bus: 'virtio': really_probe: probing driver virtio_rpmsg_bus with device virtio0
[    5.723263] virtio_rpmsg_bus virtio0: no default pinctrl state
[    5.723285] devices_kset: Moving virtio0 to end of list
[    5.723674] virtio_rpmsg_bus virtio0: rpmsg host is online
[    5.723681] driver: 'virtio_rpmsg_bus': driver_bound: bound to device 'virtio0'
[    5.723691] bus: 'virtio': really_probe: bound device virtio0 to driver virtio_rpmsg_bus
[    5.842930] remoteproc remoteproc0: remote processor 0.zynq_remoteproc is now up
[    5.857010] __fw_free_buf: fw-firmware buf=adca8440 data=b0a25000 size=569512
[    5.865327] virtio_rpmsg_bus virtio0: creating channel rpmsg-openamp-demo-channel addr 0x1
[    5.873591] device: 'virtio0:rpmsg-openamp-demo-channel': device_add
[    5.890503] bus: 'rpmsg': add device virtio0:rpmsg-openamp-demo-channel
[    5.899100] PM: Adding info for rpmsg:virtio0:rpmsg-openamp-demo-channel

```

When the  zynq_remoteproc does not create rpmsg-openamp-demo-channel 
```

[    5.691131] PM: Adding info for virtio:virtio0
[    5.704222] remoteproc remoteproc0: registered virtio0 (type 7)
[    5.721272] remoteproc remoteproc0: remote processor 0.zynq_remoteproc is now up
[    5.731339] bus: 'rpmsg': registered
[    5.747211] bus: 'virtio': add driver virtio_rpmsg_bus
[    5.747239] bus: 'virtio': driver_probe_device: matched device virtio0 with driver virtio_rpmsg_bus
[    5.747248] bus: 'virtio': really_probe: probing driver virtio_rpmsg_bus with device virtio0
[    5.747265] virtio_rpmsg_bus virtio0: no default pinctrl state
[    5.747288] devices_kset: Moving virtio0 to end of list
[    5.747689] virtio_rpmsg_bus virtio0: rpmsg host is online
[    5.747695] driver: 'virtio_rpmsg_bus': driver_bound: bound to device 'virtio0'
[    5.747706] bus: 'virtio': really_probe: bound device virtio0 to driver virtio_rpmsg_bus
[    5.880181] __fw_free_buf: fw-firmware buf=add970c0 data=b0a25000 size=569512
Wed May 24 21:40:03 UTC 2017
INIT: Entering runlevel: 5
```
Usually to solve this issue I uninstall and re-install the module and as follow:
```
   modprobe -r zynq_remoteproc 
   modprobe zynq_remoteproc

```
but, I'd like to solve the issue in order to boot load the Core 1 up when the system boot.

Do you have any advice ?
Thanks
gpresazzi

**Comment by wjliang** [comment]
Hi Gpresazzi,

When the channel is not created, it looks more like the remote side failed to setup RPMsg, which version of Linux kernel do you use and which version of OpenAMP do you use?

When it failed to create the channel, have you tried to use jtag to connect to the CPU1 and see if it is running, and check the registers to see if it crash?

"modprobe -r zynq_remoteproc " will stop CPU1 and bring back SMP mode.

Best Regards,
Wendy

**Comment by gpresazzi** [comment]
Hi Wendy,

I'm using linux kernel version 4.9 (meta-xilinx branch rel-v2017.1) and OpenAMP from meta-openamp layer (branch rel-v2017.1).

When I have connected with jtag to the board, the Core1 seems to be running. Should I wait before load module zynq_remoteproc when the system boots ?

Regards, 
Giulio

**Comment by wjliang** [comment]
HI Giulio,

If you read the CPU1 registers with "rrd" from XSDB after you have loaded the core1 with remote, do you see if the core1 is crashed, or running normally(waiting for message?)  

Just one thing, you don't need to use modprobe to unload remoteproc if you just want to stop core1, as sysfs is available on that branch, you can just do "echo stop > /sys/class/remoteproc/remoteproc0/state" to start/stop the remote.
I had thought you were using older Linux kernel because I see you loaded "/lib/firmware/updates/4.9.0-xilinx-v2017.1/firmware" and you didn't use sysfs API to specify the firmware, did you change the zynq remoteproc?

Best Regards,
Wendy

**Comment by gpresazzi** [comment]
Hi Wendy,

which register should I check? 

I've tried to stop/start the remote core 1 and it works successfully. This way is easier to stop and start core 1 when the channel is not created successfully.

I didn't change the zynq remoteprc, I'm just using the meta-openamp layer to build it.

Thanks and best regards,
Giulio

**Comment by wjliang** [comment]
Hi Giulio,

Please check the pc counter first, with the rrd command to see if the Core1 firmware has crashed at that point. or it is waiting for kick from Linux.

Best Regards,
Wendy

**Comment by gpresazzi** [comment]
Hi Wendy,

sorry for my late response. I've worked in a bare-metal app for a while, changing a lot of code.
Right now the issue does not appear anymore.

Thanks for support.
Best Regards,
Giulio
