### ISSUE TITLE
Yocto Hardknott compile ok but open-amp never appears on device, only libmetal appears

### ISSUE THREAD

**Issue by neuberfran** [OpenAMP/meta-openamp#34]
Hi,

I’m correctly generating my image Yocto-hardknott-technexion with this:
```
$ mkdir edm_yocto
$ cd edm_yocto
$ repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.52-2.1.0.xml
$ repo sync -j8
$ DISTRO=fsl-imx-x11 MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-x11-pico-imx7
$ bitbake core-image-base
```
Everything compiles OK. **I'm using the ConfFiles below:**
**local.conf**
https://gist.github.com/neuberfran/cef69a45e67e355aed12fab23a6e32e5

**bblayers.conf**
https://gist.github.com/neuberfran/d0493fec2fd311d39b7989310a04abcd

**layer.conf in $HOME/edm_yocto/sources/meta-openamp/conf**
https://gist.github.com/neuberfran/7c87469773ae0cd0860bcb7ef745c9dc

but open-amp never appears on device, only libmetal appears. **As per photos below:**
**How to solve it?**

![photo_with 03](https://user-images.githubusercontent.com/38701397/225078009-8f6eaa07-1dfc-4e83-832e-ccc46ded06b6.png)
![photo04](https://user-images.githubusercontent.com/38701397/225078033-c47dc1e2-4c30-4d9a-add8-70e50071ba55.png)

**Comment by neuberfran** [comment]
@pino-kim Hi

**Comment by moto-timo** [comment]
You might have better luck upgrading to https://github.com/TechNexion/tn-imx-yocto-manifest/blob/kirkstone_5.15.y-stable/imx-5.15.52-2.1.0.xml and using https://github.com/OpenAMP/meta-openamp/tree/master

Hardknott is end-of-life for a year now https://wiki.yoctoproject.org/wiki/Releases

**Comment by neuberfran** [comment]
@moto-timo 

As pictured below, I still haven't solved this issue.

Although I now have the Yocto Kirkstone release on my device imx7d-pico (compiled and built) on ubuntu 22.04, which is an evolution for the device and my knowledge of Yocto, But....

Below is my meta-openamp layer.conf. But I also made changes in bblayers.conf and local.conf (attached gists)

https://gist.github.com/neuberfran/09ad4da04e817f3bc15d87c5d9185fa4

![issue111](https://user-images.githubusercontent.com/38701397/227609037-38bf4bc7-7dad-4ffc-b284-bcaab2b87425.png)

**Comment by neuberfran** [comment]
Solved
